### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by LotfiAghel** [filcuc/dotherside#103]
dotherside/lib/src/DOtherSide.cpp:1067:44: error: unused parameter ‘style’ [-Werror=unused-parameter]

fix this with this change
void dos_qquickstyle_set_style([[maybe_unused]] const char *style)

void dos_qquickstyle_set_fallback_style([[maybe_unused]]const char *style)

**Comment by IrisBG** [comment]
Tested with NimQml. Can confirm, this fixes the compile error.

**Comment by filcuc** [comment]
Should be fixed in master
