### ISSUE TITLE
cmake fails to compile DMD test on OS X

### ISSUE THREAD

**Issue by 9il** [filcuc/DOtherSide#16]
```
CMake Error at D/cmake/D/CMakeTestDCompiler.cmake:45 (message):
  The D compiler "/usr/bin/dmd" is not able to compile a simple test program.

  It fails with the following output:

   Change Dir: /Users/ilya/GitHub/DOtherSide/build/CMakeFiles/CMakeTmp

  

  Run Build Command:"/usr/bin/make" "cmTryCompileExec1153283130/fast"

  /Applications/Xcode.app/Contents/Developer/usr/bin/make -f
  CMakeFiles/cmTryCompileExec1153283130.dir/build.make
  CMakeFiles/cmTryCompileExec1153283130.dir/build

  /usr/local/Cellar/cmake/3.0.2/bin/cmake -E cmake_progress_report
  /Users/ilya/GitHub/DOtherSide/build/CMakeFiles/CMakeTmp/CMakeFiles 1

  Building D object CMakeFiles/cmTryCompileExec1153283130.dir/testDCompiler

  /usr/bin/dmd CMakeFiles/cmTryCompileExec1153283130.dir/testDCompiler -c
  /Users/ilya/GitHub/DOtherSide/build/CMakeFiles/3.0.2/CMakeTmp/testDCompiler.d


  Error: cannot read file
  CMakeFiles/cmTryCompileExec1153283130.dir/testDCompiler.d

  make[1]: *** [CMakeFiles/cmTryCompileExec1153283130.dir/testDCompiler]
  Error 1

  make: *** [cmTryCompileExec1153283130/fast] Error 2

  

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  D/DQml/CMakeLists.txt:2 (project)
```

**Comment by filcuc** [comment]
Hi i don't have an osx environment but can you give us more info about the dmd version you have installed? And also the cmake version?

**Comment by 9il** [comment]
dmd compiles `testDCompiler.d`.
```
$ cmake --version
cmake version 3.0.2
$ dmd
DMD64 D Compiler v2.066.1
```
The problem in this line, it is strange.
```
  /usr/bin/dmd CMakeFiles/cmTryCompileExec1153283130.dir/testDCompiler -c
```

**Comment by 9il** [comment]
Looks like `CMakeTestDCompiler.cmake` don't work on OS X.

**Comment by filcuc** [comment]
Can you give it a try with a more recent version of CMake?
Given the heterogeneous of tools i think that, if we don't find a solution, we should write a python script for compiling both the D, Nim and C++ parts together.
I looked in the past days at a couple of build systems (bake, meson, qbs) but none support all the languages we have

**Comment by 9il** [comment]
Same error with
```$cmake --version
cmake version 3.1.3

```

**Comment by 9il** [comment]
Why do not use dub package manager for D and corresponding nimrod?

**Comment by 9il** [comment]
cmake - to build DOtherSide.
dub - to use d binding

**Comment by filcuc** [comment]
i never used dub so i cannot evaluate this, but if it's similar to Nimble (for Nim) it has a different purpose than CMake.
CMake should be used during the development phase. Nimble (and maybe DUB) in the release phase (after development).
However as i said i never used DUB

**Comment by filcuc** [comment]
The dub support is implemented here https://github.com/filcuc/dqml
