### ISSUE TITLE
DUB support

### ISSUE THREAD

**Issue by 9il** [filcuc/DOtherSide#17]
DOtherSide can be separated into

1. C library (cmake + make) with C/C++ tests (cmake + make)
2. Nimrod package (nimble) with tests (?)
3. D package (dub) with tests (using overload of `dub test`)

**Comment by 9il** [comment]
Can I create PR for (1) and (2)?

**Comment by 9il** [comment]
```
CMake Warning at CMakeLists.txt:7 (find_package):
  By not providing "FindQt5Core.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5Core", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5Core" with any
  of the following names:

    Qt5CoreConfig.cmake
    qt5core-config.cmake

  Add the installation prefix of "Qt5Core" to CMAKE_PREFIX_PATH or set
  "Qt5Core_DIR" to a directory containing one of the above files.  If
  "Qt5Core" provides a separate development package or SDK, be sure it has
  been installed.
```

**Comment by filcuc** [comment]
The last error comes because you don't have the Qt dir in path, you have to
CMAKE_PREFIX_PATH to where you installed Qt

2015-03-02 11:49 GMT+01:00 Ilya Yaroshenko <notifications@github.com>:

> CMake Warning at CMakeLists.txt:7 (find_package):
>   By not providing "FindQt5Core.cmake" in CMAKE_MODULE_PATH this project has
>   asked CMake to find a package configuration file provided by "Qt5Core", but
>   CMake did not find one.
>
>   Could not find a package configuration file provided by "Qt5Core" with any
>   of the following names:
>
>     Qt5CoreConfig.cmake
>     qt5core-config.cmake
>
>   Add the installation prefix of "Qt5Core" to CMAKE_PREFIX_PATH or set
>   "Qt5Core_DIR" to a directory containing one of the above files.  If
>   "Qt5Core" provides a separate development package or SDK, be sure it has
>   been installed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/filcuc/DOtherSide/issues/17#issuecomment-76691545>.
>



-- 
Filippo Cucchetto

**Comment by filcuc** [comment]
I always accept PR if they're good :)

2015-03-02 12:46 GMT+01:00 Filippo Cucchetto <filippocucchetto@gmail.com>:

> The last error comes because you don't have the Qt dir in path, you have
> to CMAKE_PREFIX_PATH to where you installed Qt
>
> 2015-03-02 11:49 GMT+01:00 Ilya Yaroshenko <notifications@github.com>:
>
>> CMake Warning at CMakeLists.txt:7 (find_package):
>>   By not providing "FindQt5Core.cmake" in CMAKE_MODULE_PATH this project has
>>   asked CMake to find a package configuration file provided by "Qt5Core", but
>>   CMake did not find one.
>>
>>   Could not find a package configuration file provided by "Qt5Core" with any
>>   of the following names:
>>
>>     Qt5CoreConfig.cmake
>>     qt5core-config.cmake
>>
>>   Add the installation prefix of "Qt5Core" to CMAKE_PREFIX_PATH or set
>>   "Qt5Core_DIR" to a directory containing one of the above files.  If
>>   "Qt5Core" provides a separate development package or SDK, be sure it has
>>   been installed.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/filcuc/DOtherSide/issues/17#issuecomment-76691545>.
>>
>
>
>
> --
> Filippo Cucchetto
>



-- 
Filippo Cucchetto

**Comment by filcuc** [comment]
the missing .cmake files are contained in a subfolder of you Qt installation

2015-03-02 12:51 GMT+01:00 Filippo Cucchetto <filippocucchetto@gmail.com>:

> I always accept PR if they're good :)
>
> 2015-03-02 12:46 GMT+01:00 Filippo Cucchetto <filippocucchetto@gmail.com>:
>
>> The last error comes because you don't have the Qt dir in path, you have
>> to CMAKE_PREFIX_PATH to where you installed Qt
>>
>> 2015-03-02 11:49 GMT+01:00 Ilya Yaroshenko <notifications@github.com>:
>>
>>> CMake Warning at CMakeLists.txt:7 (find_package):
>>>   By not providing "FindQt5Core.cmake" in CMAKE_MODULE_PATH this project has
>>>   asked CMake to find a package configuration file provided by "Qt5Core", but
>>>   CMake did not find one.
>>>
>>>   Could not find a package configuration file provided by "Qt5Core" with any
>>>   of the following names:
>>>
>>>     Qt5CoreConfig.cmake
>>>     qt5core-config.cmake
>>>
>>>   Add the installation prefix of "Qt5Core" to CMAKE_PREFIX_PATH or set
>>>   "Qt5Core_DIR" to a directory containing one of the above files.  If
>>>   "Qt5Core" provides a separate development package or SDK, be sure it has
>>>   been installed.
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/filcuc/DOtherSide/issues/17#issuecomment-76691545>.
>>>
>>
>>
>>
>> --
>> Filippo Cucchetto
>>
>
>
>
> --
> Filippo Cucchetto
>



-- 
Filippo Cucchetto

**Comment by 9il** [comment]
DUB works like configuration tool.

For D programmers number of steps will reduce:
1. Compile C/C++ code of DOtherSide with cmake.
2. Include this code into dub.son
```
{
       "importPaths": ["PathToTheFolderWithCDOtherSideLibrary"],
	...
	"dependencies": {
		"atmosphere_gm": "~>0.1.2"
	}
}
```
For more detailed options `subConfigurations ` can be used
```
{
	...
	"subConfigurations": {
		"DOtherSide": "dynamicLibrary"
	}
}
```

 It is good practice for DUB package to have its own git. Can you create DOtherSide community where I can create this repo?

**Comment by filcuc** [comment]
I'll create a DQml repo for mimic what is currently done at
https://github.com/filcuc/NimQml for supporting Nimble

2015-03-02 14:44 GMT+01:00 Ilya Yaroshenko <notifications@github.com>:

> DUB works like configuration tool.
>
> For D programmers number of steps will reduce:
> 1. Compile C/C++ code of DOtherSide with cmake.
> 2. Include this code into dub.son
>
> {
>        "importPaths": ["PathToTheFolderWithCDOtherSideLibrary"],
>     ...
>     "dependencies": {
>         "atmosphere_gm": "~>0.1.2"
>     }
> }
>
> For more detailed options subConfigurations can be used
>
> {
>     ...
>     "subConfigurations": {
>         "DOtherSide": "dynamicLibrary"
>     }
> }
>
> It is good practice for DUB package to have its own git. Can you create
> DOtherSide community where I can create this repo?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/filcuc/DOtherSide/issues/17#issuecomment-76713352>.
>



-- 
Filippo Cucchetto

**Comment by filcuc** [comment]
https://github.com/filcuc/DQml

2015-03-02 15:30 GMT+01:00 Filippo Cucchetto <filippocucchetto@gmail.com>:

> I'll create a DQml repo for mimic what is currently done at
> https://github.com/filcuc/NimQml for supporting Nimble
>
> 2015-03-02 14:44 GMT+01:00 Ilya Yaroshenko <notifications@github.com>:
>
>> DUB works like configuration tool.
>>
>> For D programmers number of steps will reduce:
>> 1. Compile C/C++ code of DOtherSide with cmake.
>> 2. Include this code into dub.son
>>
>> {
>>        "importPaths": ["PathToTheFolderWithCDOtherSideLibrary"],
>>     ...
>>     "dependencies": {
>>         "atmosphere_gm": "~>0.1.2"
>>     }
>> }
>>
>> For more detailed options subConfigurations can be used
>>
>> {
>>     ...
>>     "subConfigurations": {
>>         "DOtherSide": "dynamicLibrary"
>>     }
>> }
>>
>> It is good practice for DUB package to have its own git. Can you create
>> DOtherSide community where I can create this repo?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/filcuc/DOtherSide/issues/17#issuecomment-76713352>.
>>
>
>
>
> --
> Filippo Cucchetto
>



-- 
Filippo Cucchetto

**Comment by filcuc** [comment]
feel free to make a pull request there for uploading the current state of
the D bindings plus DUB.
Make another to DOtherSide for removing the D side. i'll take care for
moving the Nim stuff to the NimQml

2015-03-02 15:31 GMT+01:00 Filippo Cucchetto <filippocucchetto@gmail.com>:

> https://github.com/filcuc/DQml
>
> 2015-03-02 15:30 GMT+01:00 Filippo Cucchetto <filippocucchetto@gmail.com>:
>
>> I'll create a DQml repo for mimic what is currently done at
>> https://github.com/filcuc/NimQml for supporting Nimble
>>
>> 2015-03-02 14:44 GMT+01:00 Ilya Yaroshenko <notifications@github.com>:
>>
>>> DUB works like configuration tool.
>>>
>>> For D programmers number of steps will reduce:
>>> 1. Compile C/C++ code of DOtherSide with cmake.
>>> 2. Include this code into dub.son
>>>
>>> {
>>>        "importPaths": ["PathToTheFolderWithCDOtherSideLibrary"],
>>>     ...
>>>     "dependencies": {
>>>         "atmosphere_gm": "~>0.1.2"
>>>     }
>>> }
>>>
>>> For more detailed options subConfigurations can be used
>>>
>>> {
>>>     ...
>>>     "subConfigurations": {
>>>         "DOtherSide": "dynamicLibrary"
>>>     }
>>> }
>>>
>>> It is good practice for DUB package to have its own git. Can you create
>>> DOtherSide community where I can create this repo?
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/filcuc/DOtherSide/issues/17#issuecomment-76713352>.
>>>
>>
>>
>>
>> --
>> Filippo Cucchetto
>>
>
>
>
> --
> Filippo Cucchetto
>



-- 
Filippo Cucchetto

**Comment by 9il** [comment]
Thanks! Can you help with cmake please? I have experience with Qt under ubuntu. But with OS X something go wrong with cmake configuration:
` cmake -D CMAKE_PREFIX_PATH= ../../../../Qt/5.3/clang_64/  ..` have the same problem with     
```
Qt5CoreConfig.cmake
qt5core-config.cmake
```

**Comment by filcuc** [comment]
Try this
cmake -D CMAKE_PREFIX_PATH= ../../../../Qt/5.3/lib/cmake

2015-03-02 15:36 GMT+01:00 Ilya Yaroshenko <notifications@github.com>:

> Thanks! Can you help with cmake please? I have experience with Qt under
> ubuntu. But with OS X something go wrong with cmake configuration:
> cmake -D CMAKE_PREFIX_PATH= ../../../../Qt/5.3/clang_64/ .. have the same
> problem with
>
> Qt5CoreConfig.cmake
> qt5core-config.cmake
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/filcuc/DOtherSide/issues/17#issuecomment-76721704>.
>



-- 
Filippo Cucchetto

**Comment by filcuc** [comment]
https://github.com/filcuc/dqml

2015-03-02 15:44 GMT+01:00 Filippo Cucchetto <filippocucchetto@gmail.com>:

> Try this
> cmake -D CMAKE_PREFIX_PATH= ../../../../Qt/5.3/lib/cmake
>
> 2015-03-02 15:36 GMT+01:00 Ilya Yaroshenko <notifications@github.com>:
>
>> Thanks! Can you help with cmake please? I have experience with Qt under
>> ubuntu. But with OS X something go wrong with cmake configuration:
>> cmake -D CMAKE_PREFIX_PATH= ../../../../Qt/5.3/clang_64/ .. have the
>> same problem with
>>
>> Qt5CoreConfig.cmake
>> qt5core-config.cmake
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/filcuc/DOtherSide/issues/17#issuecomment-76721704>.
>>
>
>
>
> --
> Filippo Cucchetto
>



-- 
Filippo Cucchetto

**Comment by 9il** [comment]
Thanks!

C++/C Compiles with:
`build$ cmake -DCMAKE_PREFIX_PATH=../../../../Qt/5.3/clang_64 ..`

**Comment by 9il** [comment]
The problem was spaces =(

**Comment by filcuc** [comment]
Dub support is here https://github.com/filcuc/dqml
