### ISSUE TITLE
No response after app startup

### ISSUE THREAD

**Issue by AnyCPU** [filcuc/DOtherSide#24]
I have compiled the library and samples from sources. Compilation is ok.
When I start an app from shell I have no response at all. I modified *.nim sources (HelloWorld) to see where is problem, for example:
```nim
import NimQml
import macros
import typeinfo

proc mainProc() =
  echo "in main"
  echo "in main 7"
  var app: QApplication
  app.create()
  echo "app new"
```
In output I have only

>in main
>in main 7

I something missed?

// FreeBSD 10.1, clang 3.4.1, Nim Compiler Version 0.11.3 (2015-06-29) [FreeBSD: amd64]

**Comment by filcuc** [comment]
That's weird. But i never tested it on FreeBSD nor with clang that as far as i know it's the default compiler on FreeBSD. What branch have you cloned? develop or master? i just tested here on my Linux machine with gcc 5.1.0, Nim 0.11.3 and it works. 

Can you change the example like this?
```nim
proc mainProc() =
  echo "in main"
  echo "in main 7"
  var app = newQApplication()
  echo "app new"
```
If nothing change we can procede in two in parallel:
- You can put some echos inside the NimQml procs ans see where it hangs, so we can understand if it stops inside the Nim stuff or in the C++ library
- I try to setup a FreeBSD virtual machine with your basic configuration and see how it goes and test it with clang on Linux

**Comment by filcuc** [comment]
Ah btw using your snippet without the call to newQApplication() on my machine crashes immediately.
The reasons is that the 
```nim
var app: QApplication
```
doesn't allocate the memory pointer so is nil. Then when you call the
```nim
app.create()
```
you get a segmentation fault.

So please update the mainProc with
```nim
var app: newQApplication()
```

**Comment by filcuc** [comment]
i can reproduce it on PC-BSD

**Comment by filcuc** [comment]
I think that's some error in the mix between C and Cpp libraries.
I think it should work if you compile with nim cpp instead of nim c
However there's a bug in the Nim cpp code generator.
Filled a bug here https://github.com/nim-lang/Nim/issues/305

**Comment by AnyCPU** [comment]
Sorry for later reply. Firstly I tried to compile an examples from git repo and then an example from Nim's forum announcement about Nim Qml. In both cases I got same result.

>I think it should work if you compile with nim cpp instead of nim c
Cmake was used to compile sources. I'll try to hack it ;-)

**Comment by filcuc** [comment]
No need to hack it :) just change the file UseNim.cmake and make non executable compile with the cpp argument.

**Comment by filcuc** [comment]
I meant nim executable

**Comment by filcuc** [comment]
i solved this. The reason is that on BSD i have to manually link to pthread. Adding --passL:-lpthread on the nim compilation step and reverting to C compiler everyting works as expected. i'll make a new commit solving this bug on master.

**Comment by filcuc** [comment]
@AnyCPU can you please give it another round of test on BSD and confirm that it works now?
