### ISSUE TITLE
Qt5 connot be found ubuntu 14.04

### ISSUE THREAD

**Issue by quertiv** [filcuc/DOtherSide#33]
How do I indicate qt5 location in Ubuntu 14.04. Qt4 is install by default.

**Comment by filcuc** [comment]
i think you just have to set the QTDIR environment
```
export QTDIR=path/to/qt5/qmake
mkdir build && cd build
cmake ..
make
```

**Comment by filcuc** [comment]
Our travis file currently build the library for ubuntu 12.04

**Comment by quertiv** [comment]
Doesn't seem to work. Probably Qt issue. What about 14.04? I'm stuck on getting the compiled library on 14.04

I sure don't know what travis means, although I hear it in the forum :)

**Comment by filcuc** [comment]
i'll close this one. @quertiv  if you need to build this one find a proper PPA with a recent Qt packaged version of simply download the Qt SDK installer and build the library with it.

**Comment by filcuc** [comment]
@quertiv feel free to reopen this one if you have trouble with the compilation but issue on how to install Qt 5 are out of scope from this library
