### ISSUE TITLE
Arrays as QVariants

### ISSUE THREAD

**Issue by White-Oak** [filcuc/DOtherSide#39]
I'm developing [QML bindings for Rust](https://github.com/White-Oak/qml-rust) based on your DOtherSide bindings, and I've found that providing arrays to QML in properties is not available. 

Qt docs [mention](http://doc.qt.io/qt-5/qvariant.html#QVariant-23) creation of `QVariant` from `QList<QVariant>`, `QMap<QString, QVariant>` and `QHash<QString, QVariant>`. Two latter objects probably wouldn't be used very often, but the first one seems rather important to me, being a support for array types.

<details> <summary>Example QML code involving arrays</summary>
```qml
    PercentBarSeries {
        axisX: BarCategoryAxis { categories: ["2007", "2008", "2009", "2010", "2011", "2012" ] }
        BarSet { label: "Bob"; values: [2, 2, 3, 4, 5, 6] }
        BarSet { label: "Susan"; values: [5, 1, 2, 4, 1, 7] }
        BarSet { label: "James"; values: [3, 5, 8, 13, 5, 8] }
    }
```
</details>

**Comment by filcuc** [comment]
@White-Oak First thank you for your work i'll mention your project on the DOtherSide README :)
So you expect to receive a C array of QVariant from the binded language. Correct? i would prefear to no wrap QList..(even if it's not a big deal). I think that i start with a plan C array of QVariants.

**Comment by White-Oak** [comment]
@filcuc Well, yeah, as long as these properties can be used as shown in example below 
<details> <summary>Example QML code involving arrays and properties</summary>
```qml
    PercentBarSeries {
        axisX: BarCategoryAxis { categories: ["2007", "2008", "2009", "2010", "2011", "2012" ] }
        BarSet { label: "Bob"; values: arrayPropertyFromBindedLanguage }
        BarSet { label: "Susan"; values: [5, 1, 2, 4, 1, 7] }
        BarSet { label: "James"; values: [3, 5, 8, 13, 5, 8] }
    }
```
</details>

And also, excuse me, this is not an appropriate place for this question, but there is a `dos_chararray_delete` method [here](https://github.com/filcuc/DOtherSide/blob/master/lib/include/DOtherSide/DOtherSide.h#L65). What is this for? I may be wrong, but I have not seen a method to create `dos_charray`..

**Comment by filcuc** [comment]
@White-Oak dos_chararray_delete should be used to free the memory when you receive a string like when invoking dos_qvariant_toString. Look at the nimqml o dqml bindings. I've also started to document all the functions (with details on ownership) in the branch "oxygen" (but it's far from complete)
Ok i'll see how difficult it's to map QVariantList properties

**Comment by filcuc** [comment]
@White-Oak You can test the support for QVariantList from the relative branch.
See the test "MockQObject" example for how to declare a QMetaType::QVariantList property.

**Comment by White-Oak** [comment]
@filcuc it works, big thanks!
