### ISSUE TITLE
Help with bindings at qml_register_type (create callback)

### ISSUE THREAD

**Issue by White-Oak** [filcuc/DOtherSide#41]
<details>
<summary>The original post is here, but the problem was in other place, see second post below...</summary>
<details> 
<summary>gdb output</summary>
```
Thread 1 "qmlregister" received signal SIGSEGV, Segmentation fault.
__cxxabiv1::__dynamic_cast (src_ptr=0x7fffedeb3f40, 
   src_type=0x7ffff5ed3690 <typeinfo for QObject>,
   dst_type=0x55555596cd58 <typeinfo for DOS::DosQObject>, src2dst=0) 
   at /build/gcc-multilib/src/gcc/libstdc++-v3/libsupc++/dyncast.cc:72
72      /build/gcc-multilib/src/gcc/libstdc++-v3/libsupc++/dyncast.cc: No such file or directory.
```
</details>

As far as I can understand that's coming from 
```
m_impl = dynamic_cast<DosQObject *>(static_cast<QObject *>(impl));
```
So this impl is `bindedQObject` from `typedef void( * CreateDObject) (int id, void *wrapper, void **dosQObject, void **bindedQObject)`.

I'm storing in this `bindedQObject` the same pointer I'm passing to `dos_qobject_create()` as a first argument (`dObjectPointer`):
```
Pointer passed to dos_qobject_create() is: 0x7fffedeb3f40
Pointer stored in bindedQObject object is: 0x7fffedeb3f40
```
Am I doing something wrong? :(
</details>

**Comment by filcuc** [comment]
@White-Oak Sorry for that. I hope it didn't take you too long to solve it.
