### ISSUE TITLE
Add support for QAbstractItemModel

### ISSUE THREAD

**Issue by fneddy** [filcuc/DOtherSide#48]
QAbstractItemModel is needed to provide tree-like models to QML components.

**Comment by filcuc** [comment]
This should be fixed in my branch qaim

**Comment by filcuc** [comment]
@fneddy It should be included in the next release. Hope between this and next week

**Comment by filcuc** [comment]
I prefear to keep this open until i release to master

**Comment by filcuc** [comment]
Fixed in v0.6.0
