### ISSUE TITLE
add support for QQuickImageProvider

### ISSUE THREAD

**Issue by royneary** [filcuc/DOtherSide#53]
Currently there's no possibility to dynamically add and display images, correct? This is quite a common requirement I think, let's say I want to build an image gallery application which loads images from a database.

I saw there was [an idea](https://wiki.dlang.org/GSOC_2016_Ideas#QML_Bindings) once to make a GSoC project out of this. I guess it didn't happen. I'm writing this because I'd like to know if someone else currently is interested in this and wants to collaborate. My goal would be to add dynamic image loading to [qml-rust](https://github.com/White-Oak/qml-rust).

**Comment by filcuc** [comment]
Most of the things in the GSOC has alraedy been done but yes there's no support for image providers yet. Adding it should be quite easy
