### ISSUE TITLE
Support for QModelIndex::internalPointer

### ISSUE THREAD

**Issue by drug007** [filcuc/DOtherSide#57]
As I understand the only reason this support is absent is man power lack?

**Comment by filcuc** [comment]
No. It's Just the evolution of the library. Initially we supported only list models where internal pointer is not useful but now we supported most qaim features. So we can add it.

**Comment by filcuc** [comment]
You can see that we have support for it inside the createIndex function. So it's just a matter of exposing it in qmodelindex. I can do it this evening

**Comment by drug007** [comment]
Probably I expressed my thoughts wrong way. But I understood you - I meant the same. In my spare time I tried to port [simple tree model for qml](https://github.com/hvoigt/qt-qml-treeview) from c++ to dlang and it needed `internalPointer`. I just wanted to clarify this point. Thanks.

**Comment by filcuc** [comment]
@drug007 please notify me if you port the tree example in dlang :) i'm interested

**Comment by drug007** [comment]
Thanks!
do not promise I do it due to lack of time right now, but if then definitely notify you.
