### ISSUE TITLE
Q_DECLARE_METATYPE analog

### ISSUE THREAD

**Issue by drug007** [filcuc/DOtherSide#59]
This macro is used to add supporting for custom type to QVariant. Is there a way to use it from binded language? That is define a CustomType in binded language and in some way register it in the Qt type system?

**Comment by filcuc** [comment]
After having thinked about it a little i think yes it can be done. I can
prototype a possible implementation. However the binding language should
expose a couple of functions for mailing the QVariant copiable: a copy
function and a default constructor plus eventual relational functions.

Il 16 apr 2017 18:38, "drug007" <notifications@github.com> ha scritto:

**Comment by drug007** [comment]
I just use example of registering qml type from dqml and it works like a charm without this macro. So for me the issue can be closed.
