### ISSUE TITLE
Add support for setting the QQuickControls 2 style

### ISSUE THREAD

**Issue by filcuc** [filcuc/DOtherSide#63]

**Comment by SShrike** [comment]
Are there any updates on this? I'm in the early stages of working on an Anki-like application implemented in Rust and QML and would like to use the Material Design theme in QtQuickControls 2.

**Comment by filcuc** [comment]
@SShrike done

**Comment by SShrike** [comment]
Holy shit man, that was quick. Thanks a tonne 🎉
