### ISSUE TITLE
How to set non-default path to Qt?

### ISSUE THREAD

**Issue by r3d9u11** [filcuc/DOtherSide#71]
Hi. I've installed qt 5.10.1 with qt-creator into path /home/username/Qt via online-installator qt-unified-linux-x64-3.0.2-online.run

Is it possible to make this library and define path to my current Qt's dir?

```
/home/username/Qt/5.10.1/gcc_64 $ ls
bin  doc  include  lib  libexec  mkspecs  phrasebooks  plugins  qml  resources  translations
```

Thanks.

**Comment by filcuc** [comment]
First be sure to compile and use this library with the same Qt versions.
From your question i don't get if you have a problem in compiling the DOtherSide bindings or at runtime when using a 3rdparty binding (nimqml, rustqml or dqml).
1) Compilation
If you installed Qt in a different path you can make cmake look for your Qt libraries during configuration. Usually you need to point the cmake to the /path/to/Qt/lib/cmake/Qt[Core, Gui, Quick] etc directories
2) At runtime you can override the default search path for dynamic libraries (.so, .dll etc) by setting the LD_LIBRARY_PATH (on linux)
