### ISSUE TITLE
An additional components support

### ISSUE THREAD

**Issue by r3d9u11** [filcuc/DOtherSide#72]
Hi. What qt-packages includes in this library? Is it possible to use an additional components like a Qt5Charts, Qt5QuickControls2, etc.?

**Comment by r3d9u11** [comment]
it works
![13](https://user-images.githubusercontent.com/15020827/36748734-c931aa00-1c09-11e8-8963-4b10ef0860b7.png)
megacool!

**Comment by filcuc** [comment]
@r3d9u11 From the Qml side you can use whatever you want. The only limitations you can have are how you can exchange data between the binded language and the Qt side. But overall you can do pretty much everything given that we support QObjects and QAbstractItemModels.

**Comment by filcuc** [comment]
The library doesn't want to be a full Qt binding. It has only the minimum number of features for enabling the use of Qml. For other means use your binded language standard library
