### ISSUE TITLE
insufficient headers installed by CMake?

### ISSUE THREAD

**Issue by stefantalpalaru** [filcuc/DOtherSide#81]
CMake only installs 2 headers: "DOtherSide.h" and "DOtherSideTypes.h", but "test/test_dotherside.cpp" uses 3 more:
```C
#include <DOtherSide/DosQObject.h>
#include <DOtherSide/DosQMetaObject.h>
#include <DOtherSide/DosQObject.h>
#include <DOtherSide/DosQAbstractItemModel.h>
```
so it couldn't be compiled just with the installed headers.

Even more are available in "lib/include/DOtherSide". Shouldn't they all be installed?

**Comment by filcuc** [comment]
No. Test usually gets built from sources by cloning the repo and should
basically use the local header files and not the one installed in the user
system (think about the case where the installed headers are older than the
one cloned through git). Dotherside install only the public headers the
rest are private headers. The public headers are enough for the end user
for using the library and usually they export the public functions
(dllexport/dllimport on Windows or visibility pragma with gcc).

Il Mer 24 Apr 2019, 15:35 Ștefan Talpalaru <notifications@github.com> ha
scritto:

**Comment by stefantalpalaru** [comment]
I was thinking about C clients of this library, not just those Nim/D/Rust wrappers that have their own converted headers.
Are opaque pointers like `typedef void DosQObject` enough for that?

**Comment by filcuc** [comment]
There's only one API. The one exported through public headers. D/Nim/Rust bindings or C clients the all the same interface/API and headers. In other words bindings don't use the private headers and btw that is basically impossible given that private headers are c++ headers and not C headers.
