### ISSUE TITLE
Question about using Q_OBJECT with DOtherside

### ISSUE THREAD

**Issue by richard-ramos** [filcuc/dotherside#91]
Hi there, @filcuc.
Is it possible to use QT MOC within DOtherside? I was trying to follow the solution to this question: https://stackoverflow.com/a/40313601, and after attempting to implement the same inside DOtherSide.cpp, while building the project I ended up with the following error:
```
AutoMoc error
-------------
"SRC:/lib/src/DOtherSide.cpp"
contains a "Q_OBJECT" macro, but does not include "DOtherSide.moc"!
Consider to
  - add #include "DOtherSide.moc"
  - enable SKIP_AUTOMOC for this file

make[3]: *** [lib/CMakeFiles/DOtherSideStatic_autogen.dir/build.make:77: lib/CMakeFiles/DOtherSideStatic_autogen] Error 1
make[3]: Leaving directory '/home/richard/status/nim-status-client/vendor/DOtherSide/build'
make[2]: *** [CMakeFiles/Makefile2:141: lib/CMakeFiles/DOtherSideStatic_autogen.dir/all] Error 2
make[2]: Leaving directory '/home/richard/status/nim-status-client/vendor/DOtherSide/build'
make[1]: *** [Makefile:149: all] Error 2
```

**Comment by filcuc** [comment]
@richard-ramos that error message is just saying that somehow the translation unit of DOtherSide.cpp contains a Q_OBJECT macro e is not processed by moc for fixing this you have two options:
1) Move the Q_OBJECT is its' own .h/.cpp pair. In this way MOC see the .h header and automatically add to those to be MOCked
2) Simply add `#include "DOtherSide.moc" as the last line in DOtherSide.cpp
Remember to rerun cmake configure/generate pair and eventually rebuild the whole thing for "waking up" MOC

**Comment by filcuc** [comment]
@richard-ramos  can i mark this solved?

**Comment by richard-ramos** [comment]
Yes, thank you for the help!
